name: Fixture Docker action with all Docker entrypoints
description: Exercises pre-entrypoint, entrypoint, and post-entrypoint.

runs:
  using: docker
  image: Dockerfile
  pre-entrypoint: /github/action/pre-entrypoint.sh
  entrypoint: /github/action/entrypoint.sh
  post-entrypoint: /github/action/post-entrypoint.sh
  args:
    - fixture docker arg
